site_name: Aliyun 计算巢 x Demo
theme: 
  name: aliyuncomputenestROSTemplateFormatVersion: '2015-09-01'
Conditions:
  CreateVpcConditions:
    Fn::Equals:
      - NewVPC
      - Ref: VpcOption
Parameters:
  VpcOption:
    Type: String
    AllowedValues:
      - NewVPC
      - ExistingVPC
    AssociationPropertyMetadata:
      ValueLabelMapping:
        NewVPC:
          zh-cn: 新建专有网络
          en: New VPC
        ExistingVPC:
          zh-cn: 已有专有网络
          en: Existing VPC
    Label:
      en: Select Existing or New VPC
      zh-cn: 选择已有/新建的专有网络
    Required: true
    Default: NewVPC
  VpcCidrBlock:
    Type: String
    Label:
      en: VPC CIDR IPv4 Block
      zh-cn: 专有网络IPv4网段
    Description:
      zh-cn: VPC的ip地址段范围，<br>您可以使用以下的ip地址段或其子网:<br><font color='green'>[10.0.0.0/8]</font><br><font color='green'>[172.16.0.0/12]</font><br><font color='green'>[192.168.0.0/16]</font>
      en: 'The ip address range of the VPC in the CidrBlock form; <br>You can use the following ip address ranges and their subnets: <br><font color=''green''>[10.0.0.0/8]</font><br><font color=''green''>[172.16.0.0/12]</font><br><font color=''green''>[192.168.0.0/16]</font>'
    Default: 192.168.0.0/16
    Required:
      Fn::Equals:
        - NewVPC
        - ${VpcOption}
    AssociationProperty: ALIYUN::VPC::VPC::CidrBlock
    AssociationPropertyMetadata:
      Visible:
        Condition:
          Fn::Equals:
            - NewVPC
            - ${VpcOption}
  VSwitchCidrBlock:
    Type: String
    Label:
      en: VSwitch CIDR Block
      zh-cn: 交换机子网网段
    Description:
      zh-cn: 必须属于VPC的子网段。
      en: Must belong to the subnet segment of VPC.
    Default: 192.168.1.0/24
    Required:
      Fn::Equals:
        - NewVPC
        - ${VpcOption}
    AssociationProperty: ALIYUN::VPC::VSwitch::CidrBlock
    AssociationPropertyMetadata:
      VpcCidrBlock: VpcCidrBlock
      Visible:
        Condition:
          Fn::Equals:
            - NewVPC
            - ${VpcOption}
  PayType:
    Type: String
    Label:
      en: ECS Instance Charge Type
      zh-cn: 付费类型
    Default: PrePaid
    AllowedValues:
      - PrePaid
      - PostPaid
    AssociationProperty: ChargeType
    AssociationPropertyMetadata:
      LocaleKey: InstanceChargeType
  PayPeriodUnit:
    Type: String
    Label:
      en: Pay Period Unit
      zh-cn: 购买资源时长周期
    Default: Month
    AllowedValues:
      - Month
    AssociationProperty: PayPeriodUnit
    AssociationPropertyMetadata:
      ValueLabelMapping:
        Month: 月
      Visible:
        Condition:
          Fn::Not:
            Fn::Equals:
              - ${PayType}
              - PostPaid
  PayPeriod:
    Type: Number
    Label:
      en: Period
      zh-cn: 购买资源时长
    Default: 12
    AllowedValues:
      - 3
      - 12
    AssociationProperty: PayPeriod
    AssociationPropertyMetadata:
      Visible:
        Condition:
          Fn::Not:
            Fn::Equals:
              - ${PayType}
              - PostPaid
  EcsInstanceType:
    Type: String
    Label:
      en: Instance Type
      zh-cn: 实例类型
    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
    AssociationPropertyMetadata:
      ZoneId: ${ZoneId}
      InstanceChargeType: ${PayType}
  SystemDiskCategory:
    Type: String
    AllowedValues:
      - cloud_efficiency
      - cloud_essd
      - cloud_essd_entry
    Label:
      en: System Disk Category
      zh-cn: 系统盘类型
    AssociationPropertyMetadata:
      LocaleKey: DiskCategory
  SystemDiskSize:
    Type: Number
    Label:
      zh-cn: 系统盘空间 (GB)
      en: System Disk Space (GB)
    MinValue: 40
    MaxValue: 2000
  InternetChargeType:
    Type: String
    Label:
      zh-cn: 带宽付费类型
      en: Internet Charge Type
    AssociationPropertyMetadata:
      ValueLabelMapping:
        PayByTraffic: 按流量计费
        PayByBandwidth: 按固定带宽计费
    AllowedValues:
      - PayByBandwidth
      - PayByTraffic
  InternetMaxBandwidthOut:
    Type: Number
    Label:
      zh-cn: 公网带宽 (Mbps)
      en: Internet Max Bandwidth Out (Mbps)
    MinValue: 1
    MaxValue: 100
  InstancePassword:
    NoEcho: true
    Type: String
    Description:
      en: Server login password, Length 8-30, must contain three(Capital letters, lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
      zh-cn: 服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
    AllowedPattern: '^[a-zA-Z0-9-\(\)\`\~\!\@\#\$\%\^\&\*\_\-\+\=\|\{\}\[\]\:\;\<\>\,\.\?\/]*$'
    Label:
      en: Instance Password
      zh-cn: 实例密码
    ConstraintDescription:
      en: Length 8-30, must contain three(Capital letters, lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
      zh-cn: 长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
    MinLength: 8
    MaxLength: 30
    AssociationProperty: ALIYUN::ECS::Instance::Password
    AssociationPropertyMetadata:
      Random: true
  ZoneId:
    Type: String
    Label:
      en: Zone ID
      zh-cn: 可用区ID
    AssociationProperty: ALIYUN::ECS::Instance::ZoneId
    AssociationPropertyMetadata:
      DefaultValueStrategy: random
      InstanceChargeType: ${PayType}
      SystemDiskCategory: cloud_essd
      InstanceType: ${EcsInstanceType}
  VpcId:
    Type: String
    Label:
      en: VPC ID
      zh-cn: 专有网络VPC实例ID
    AssociationProperty: 'ALIYUN::ECS::VPC::VPCId'
    Required:
      Fn::Equals:
        - ExistingVPC
        - ${VpcOption}
    Default: ''
    AssociationPropertyMetadata:
      AutoSelectFirst: true
      Visible:
        Condition:
          Fn::Equals:
            - ExistingVPC
            - ${VpcOption}
  VSwitchId:
    Type: String
    Label:
      en: VSwitch ID
      zh-cn: 交换机实例ID
    Default: ''
    AssociationProperty: 'ALIYUN::ECS::VSwitch::VSwitchId'
    Required:
      Fn::Equals:
        - ExistingVPC
        - ${VpcOption}
    AssociationPropertyMetadata:
      AutoSelectFirst: true
      VpcId: ${VpcId}
      ZoneId: ${ZoneId}
      Visible:
        Condition:
          Fn::Equals:
            - ExistingVPC
            - ${VpcOption}
Resources:
  # 新建vpc
  EcsVpc:
    Type: ALIYUN::ECS::VPC
    Condition: CreateVpcConditions
    Properties:
      VpcName:
        Ref: ALIYUN::StackName
      CidrBlock:
        Ref: VpcCidrBlock
  # 新建vswitch
  EcsVSwitch:
    Condition: CreateVpcConditions
    Type: ALIYUN::ECS::VSwitch
    Properties:
      VSwitchName:
        Ref: ALIYUN::StackName
      VpcId:
        Ref: EcsVpc
      ZoneId:
        Ref: ZoneId
      CidrBlock:
        Ref: VSwitchCidrBlock
  SecurityGroup:
    Type: ALIYUN::ECS::SecurityGroup
    Properties:
      SecurityGroupName:
        Ref: ALIYUN::StackName
      VpcId:
        Fn::If:
          - CreateVpcConditions
          - Ref: EcsVpc
          - Ref: VpcId
      SecurityGroupIngress:
        - PortRange: 80/80
          Priority: 1
          SourceCidrIp: 0.0.0.0/0
          IpProtocol: tcp
          NicType: internet
        - PortRange: 22/22
          Priority: 1
          SourceCidrIp: 0.0.0.0/0
          IpProtocol: tcp
          NicType: internet
  InstanceGroup:
    Type: ALIYUN::ECS::InstanceGroup
    Properties:
      # 付费类型
      InstanceChargeType:
        Ref: PayType
      PeriodUnit:
        Ref: PayPeriodUnit
      Period:
        Ref: PayPeriod
      VpcId:
        Fn::If:
          - CreateVpcConditions
          - Ref: EcsVpc
          - Ref: VpcId
      VSwitchId:
        'Fn::If':
          - CreateVpcConditions
          - Ref: EcsVSwitch
          - Ref: VSwitchId
      ZoneId:
        Ref: ZoneId
      SecurityGroupId:
        Ref: SecurityGroup
      ImageId: centos_7_9_x64_20G_alibase_20240403.vhd
      Password:
        Ref: InstancePassword
      SystemDiskCategory:
        Ref: SystemDiskCategory
      SystemDiskSize:
        Ref: SystemDiskSize
      MaxAmount: 1
      InstanceType:
        Ref: EcsInstanceType
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      InternetChargeType:
        Ref: InternetChargeType
      IoOptimized: optimized
Outputs:
  Cloudreve_address:
    Description:
      en: Cloudreve address.
      zh-cn: Cloudreve 访问页面
    Value:
      Fn::Sub:
        - http://${ServerAddress}:80
        - ServerAddress:
            Fn::Select:
              - 0
              - Fn::GetAtt:
                  - InstanceGroup
                  - PublicIps
Metadata:
  ALIYUN::ROS::Interface:
    ParameterGroups:
      - Parameters:
          - PayType
          - PayPeriodUnit
          - PayPeriod
        Label:
          default: 付费类型配置
      - Parameters:
          - EcsInstanceType
          - InternetChargeType
          - InternetMaxBandwidthOut
          - SystemDiskCategory
          - SystemDiskSize
          - InstancePassword
        Label:
          default: 服务器基础配置
      - Parameters:
          - ZoneId
          - VpcOption
          - VpcId
          - VSwitchId
          - VpcCidrBlock
          - VSwitchCidrBlock
        Label:
          default: 配置专有网络
    QuickDeployConfig:
      PackageFields:
        - Key: EcsInstanceType
        - Key: SystemDiskCategory
          Label:
            zh-cn: 系统盘
            en: System Disk
          Value: '${SystemDiskCategory} / ${SystemDiskSize} GB'
        - Key: InternetChargeType
          Label:
            zh-cn: 公网带宽
            en: Internet Charge Type
          Value: '${InternetChargeType } / ${InternetMaxBandwidthOut} Mbps'
        - Key: PayType
          Label:
            zh-cn: 付费类型
            en:  Pay Type
          Value: '${PayType}'
        - Key: PayPeriodUnit
          Label:
            zh-cn: 付费时长
            en: Pay Period
          Value: '${PayPeriod} ${PayPeriodUnit}'
      PredefinedParameters:
        - Name: 热卖套餐，特价99元/年（限购1台）
          Parameters:
            EcsInstanceType: ecs.e-c1m1.large
            SystemDiskCategory: cloud_essd_entry
            SystemDiskSize: 40
            InternetChargeType: PayByBandwidth
            InternetMaxBandwidthOut: 3
            PayPeriodUnit: Month
            PayPeriod: 12
            PayType: PrePaid
          OrderList:
            - EcsInstanceType
            - SystemDiskCategory
            - SystemDiskSize
            - InternetChargeType
            - InternetMaxBandwidthOut
            - PayPeriodUnit
            - PayPeriod
            - PayType
          Type: Normal
          Description: 固定带宽不限流量，新老同享，上云首选！
        - Name: 尝鲜套餐，只需0.3元/小时
          Parameters:
            EcsInstanceType: ecs.e-c1m1.large
            SystemDiskCategory: cloud_essd_entry
            SystemDiskSize: 40
            InternetChargeType: PayByBandwidth
            InternetMaxBandwidthOut: 3
            PayPeriodUnit: Month
            PayPeriod: 12
            PayType: PostPaid
          OrderList:
            - EcsInstanceType
            - SystemDiskCategory
            - SystemDiskSize
            - InternetChargeType
            - InternetMaxBandwidthOut
            - PayPeriodUnit
            - PayPeriod
            - PayType
          Type: Normal
          Description: 可用300元学生专属代金券抵扣！<a href="https://university.aliyun.com" target="_blank">立即领取</a>
        - Name: 自定义套餐
          Parameters: {}
          OrderList:
            - EcsInstanceType
            - SystemDiskCategory
            - SystemDiskSize
            - InternetChargeType
            - InternetMaxBandwidthOut
            - PayPeriodUnit
            - PayPeriod
            - PayType
          Type: Custom
      CustomFields:
        - Key: InstancePassword
      CostRelatedKeys:
        - RegionId
        - PayPeriod
      AutomaticZone:
        ZoneIdKey: ZoneId